### ISSUE TITLE
Shadow error

### ISSUE THREAD

**Issue by muniss950** [prasanthrangan/hyde-themes#24]
Recent update on hyprland has changed the structure for shadow,which is creating error for all themes.

![image](https://github.com/user-attachments/assets/3ea195dd-6cd0-4851-9361-a5f3f986870d)

**Comment by XeCipher** [comment]
This is because of [change log](https://hyprland.org/news/update45/).
Just run update
```
cd ~/HyDE/Scripts
git pull
./install.sh -r
```
It has been fixed already.

**Comment by muniss950** [comment]
Thanks!,it worked.
I thought it was not fixed as the configs in this repo still have the old variables.
